kind: PersistentVolume
apiVersion: v1
metadata:
  name: workflow-nfs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/romain/Workspaces/Ops/kubeflow/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workflow-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
