kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: svc-list
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: svc-list
subjects:
- kind: Group
  name: system:serviceaccounts  # For all service accounts
  namespace: default
roleRef:
  kind: ClusterRole
  name: svc-list
  apiGroup: rbac.authorization.k8s.io
