kind: PersistentVolume
apiVersion: v1
metadata:
  name: workflow-nfs
  labels:
    type: local
  namespace: kubeflow
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/mnist"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workflow-pvc
  namespace: kubeflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
